Q := Rationals();
KT<T> := FunctionField(Q);
P<x> := PolynomialRing(KT);

N :=
    x^8
    + 4*x^7
    + 12*x^6
    + 32*x^5
    + 87*x^4
    + 220*x^3
    + 444*x^2
    + 360*x
    - 8;
D :=
    x^4
    + 4*x^3
    + 8*x^2
    + 8*x
    + 4;
fiber := N-T*D;
assert IsIrreducible(fiber);

target_cubic := T^3 - T^2 - 5833*T + 207037;
fiber_discriminant := Discriminant(fiber);
assert fiber_discriminant eq
    -3276800000*target_cubic^3;
discriminant_square_class := -5*target_cubic;
assert IsSquare(KT!(
    fiber_discriminant/discriminant_square_class
));
assert not IsSquare(KT!(
    target_cubic/discriminant_square_class
));

G, roots, root_map := GaloisGroup(fiber);
assert #G eq 40320;
assert GroupName(G) eq "S8";
assert #DerivedGroup(G) eq 20160;

// S8 has a unique quadratic subfield, generated by the square root of the
// fiber discriminant.  The elliptic base adjoins sqrt(target_cubic), a
// different square class, so the base-changed monodromy remains S8.
print "B011_DEGREE8_MONODROMY_VERIFIED";
print "rational_map_group", GroupName(G);
print "rational_map_order", #G;
print "elliptic_base_group", "S8";
print "discriminant_square_class", "-5*target_cubic";
quit;
