Q := Rationals();
KT<T> := FunctionField(Q);
P<x> := PolynomialRing(KT);

N :=
    3*x^6
    - 30*x^5
    + 81*x^4
    - 296/3*x^3
    + 184/3*x^2
    - 848/27;
D :=
    x^6
    - 6*x^5
    + 9*x^4
    + 40/9*x^3
    - 40/3*x^2
    + 400/81;
fiber := N-T*D;
assert IsIrreducible(fiber);

target_cubic := T^3 - 27*T + 90;
fiber_discriminant := Discriminant(fiber);
assert fiber_discriminant eq
    2^43/3^6*(25*T + 159)*target_cubic^2;
discriminant_square_class := 2*(25*T + 159);
assert IsSquare(KT!(fiber_discriminant/discriminant_square_class));
assert not IsSquare(KT!(target_cubic/discriminant_square_class));

G, roots, root_map := GaloisGroup(fiber);
identifier, degree := TransitiveGroupIdentification(G);
assert #G eq 720;
assert degree eq 6 and identifier eq 16;
assert GroupName(G) eq "S6";
assert #DerivedGroup(G) eq 360;

// S6 has a unique quadratic subfield, generated by the square root of the
// fiber discriminant.  The elliptic base adjoins sqrt(target_cubic), a
// different square class, so the base-changed monodromy remains S6.
print "B011_DEGREE6_MONODROMY_VERIFIED";
print "rational_map_group", GroupName(G);
print "rational_map_order", #G;
print "elliptic_base_group", "S6";
print "exceptional_PGL2_5", false;
quit;
