"""
Fixed-field equations for the Galois-closure complementary quotient.

Let phi(t)=N(t)/D(t), let w^2=f(z) be the elliptic double cover, and
let t1,t2 be distinct roots of N(t)-z*D(t).  The off-diagonal component
has function field generated by t1,t2,w.  The involution

    (t1,t2,w) -> (t2,t1,-w)

has invariant generators

    s=t1+t2, p=t1*t2, q=w*(t1-t2).

The quotient is therefore cut out by the two coefficients of the
remainder of N(T)-z*D(T) modulo T^2-s*T+p, together with

    q^2=f(z)*(s^2-4*p).
"""


def _lift_univariate_polynomial(poly, target_variable):
    target_ring = target_variable.parent()
    return sum(
        target_ring(poly[index]) * target_variable^index
        for index in range(poly.degree() + 1)
    )


def galois_complement_equations(
    rational_map,
    elliptic_rhs,
    variable_names=("s", "p", "z", "q"),
):
    """
    Return the invariant equations for the complementary quotient.

    INPUT:

    - ``rational_map`` -- a univariate rational function N(t)/D(t);
    - ``elliptic_rhs`` -- the univariate polynomial f(z) in w^2=f(z).

    The returned dictionary includes the exact Euclidean-division
    certificate and the equation of the unordered pair curve obtained by
    eliminating z from the two remainder coefficients.
    """
    numerator = rational_map.numerator()
    denominator = numerator.parent()(
        rational_map.denominator()
    )

    coefficient_ring = numerator.base_ring()
    invariant_ring = PolynomialRing(
        coefficient_ring,
        names=variable_names,
        order="degrevlex",
    )
    s, p, z, q = invariant_ring.gens()
    auxiliary_ring = PolynomialRing(invariant_ring, names=("T",))
    T = auxiliary_ring.gen()

    lifted_numerator = _lift_univariate_polynomial(numerator, T)
    lifted_denominator = _lift_univariate_polynomial(denominator, T)
    fiber_polynomial = lifted_numerator - z * lifted_denominator
    pair_polynomial = T^2 - s*T + p
    quotient, remainder = fiber_polynomial.quo_rem(pair_polynomial)
    assert remainder.degree() <= 1
    assert fiber_polynomial == quotient*pair_polynomial + remainder

    numerator_remainder = lifted_numerator.mod(pair_polynomial)
    denominator_remainder = lifted_denominator.mod(pair_polynomial)
    numerator_coefficients = [
        invariant_ring(numerator_remainder[index])
        for index in range(2)
    ]
    denominator_coefficients = [
        invariant_ring(denominator_remainder[index])
        for index in range(2)
    ]
    remainder_coefficients = [
        invariant_ring(remainder[index])
        for index in range(2)
    ]

    pair_relation = (
        numerator_coefficients[0]*denominator_coefficients[1]
        - numerator_coefficients[1]*denominator_coefficients[0]
    )
    lifted_elliptic_rhs = invariant_ring(
        elliptic_rhs(z)
    )
    orientation_relation = (
        q^2 - lifted_elliptic_rhs*(s^2-4*p)
    )

    return {
        "ring": invariant_ring,
        "variables": {
            "s": s,
            "p": p,
            "z": z,
            "q": q,
        },
        "auxiliary_ring": auxiliary_ring,
        "fiber_polynomial": fiber_polynomial,
        "pair_polynomial": pair_polynomial,
        "division_quotient": quotient,
        "division_remainder": remainder,
        "remainder_coefficients": remainder_coefficients,
        "pair_relation": invariant_ring(pair_relation),
        "orientation_relation": invariant_ring(orientation_relation),
        "equations": remainder_coefficients + [
            invariant_ring(orientation_relation)
        ],
    }


def certify_galois_complement_equations(certificate):
    """Recheck all exact identities in an equation certificate."""
    fiber_polynomial = certificate["fiber_polynomial"]
    pair_polynomial = certificate["pair_polynomial"]
    quotient = certificate["division_quotient"]
    remainder = certificate["division_remainder"]
    assert fiber_polynomial == quotient*pair_polynomial + remainder
    assert remainder.degree() <= 1
    assert certificate["orientation_relation"] in certificate["ring"]
    assert len(certificate["equations"]) == 3
    return True
