"""
Construct exact members of the generic degree-5 family.

For each rational parameter pair (a,b), this script:

1. computes the quadratic polynomial for the fourth elliptic branch value;
2. constructs the quadratic field K generated by one branch value e;
3. constructs the genus-2 pullback of y^2=t(t-1)(t-e);
4. certifies the degree-5 map to the Legendre elliptic curve; and
5. tests the normalization conic over Q and over K.

Run from the repository root:

    HOME=/tmp/sagehome sage computations/sage/census_degree5_family.sage
"""

import json
from datetime import datetime
from pathlib import Path
from time import perf_counter


started = perf_counter()
root = Path.cwd()

P.<A, B, X, T> = PolynomialRing(QQ, 4)
F1_generic = X^2 + (2*A + 2*B + A^2)*X + 2*A*B + B^2
F2_generic = (2*A + 1)*X^2 + (A^2 + 2*A*B + 2*B)*X + B^2
cover_generic = X*F1_generic^2 - T*F2_generic^2
branch_resultant = cover_generic.resultant(
    cover_generic.derivative(X), X
)
branch_quadratic_generic = P(
    branch_resultant
    / (
        256
        * A^12
        * B^4
        * (A + B + 1)^4
        * T^2
        * (T - 1)^2
    )
)
assert branch_quadratic_generic.degree(T) == 2

parameter_pairs = [
    (-4, 1),
    (-3, 1),
    (-3, 2),
    (-2, 3),
    (-1, 2),
    (1, 1),
    (1, 2),
    (1, 3),
    (2, 1),
    (2, 3),
    (3, 1),
    (3, 2),
    (4, 1),
    (5, 1),
    (7, 1),
]

examples = []
for av, bv in parameter_pairs:
    if av*bv*(av + bv + 1)*(2*av + 1) == 0:
        continue

    Qt.<t> = PolynomialRing(QQ)
    branch_quadratic = Qt(
        branch_quadratic_generic(A=av, B=bv, X=0, T=t)
    )
    if branch_quadratic.degree() != 2 or branch_quadratic.discriminant() == 0:
        continue
    if not branch_quadratic.is_irreducible():
        continue

    K.<e> = NumberField(branch_quadratic)
    Kx.<x> = PolynomialRing(K)
    a = K(av)
    b = K(bv)
    F1 = x^2 + (2*a + 2*b + a^2)*x + 2*a*b + b^2
    F2 = (2*a + 1)*x^2 + (a^2 + 2*a*b + 2*b)*x + b^2
    F3 = x^2 - (a^2 - 2*b)*x + b^2
    phi_num = x*F1^2
    phi_den = F2^2
    assert phi_num - phi_den == (x - 1)*F3^2
    assert gcd(phi_num, phi_den) == 1
    assert max(phi_num.degree(), phi_den.degree()) == 5

    pullback_numerator = (
        phi_num
        * (phi_num - phi_den)
        * (phi_num - e*phi_den)
    )
    source_polynomial = pullback_numerator.squarefree_part()
    square_quotient = pullback_numerator // source_polynomial
    assert pullback_numerator == source_polynomial*square_quotient
    assert square_quotient.is_square()
    square_multiplier = square_quotient.sqrt()
    assert square_multiplier^2 == square_quotient
    assert source_polynomial.is_squarefree()
    source_curve = HyperellipticCurve(source_polynomial)
    assert source_curve.genus() == 2

    # If y^2=source_polynomial, then
    # (t,Y)=(phi_num/phi_den, y*square_multiplier/F2^3)
    # lies on Y^2=t(t-1)(t-e).
    assert (
        source_polynomial*square_multiplier^2*phi_den^3
        == pullback_numerator*F2^6
    )

    j_target = K(
        256*(1 - e + e^2)^3/(e^2*(1 - e)^2)
    )

    # The normalization conic y^2=L*m^2+M*m+N is equivalent to
    # U^2-4*L*Y^2-D*Z^2=0, where D=M^2-4*L*N.
    L = QQ(av^4 + 2*av^3 + 2*av^2*bv + av^2 + bv^2)
    M = QQ(2*bv*(av + bv)*(av^2 + bv))
    N = QQ(bv^3*(2*av + bv))
    D = M^2 - 4*L*N
    conic_Q = Conic(QQ, [1, -4*L, -D])
    soluble_Q, point_or_obstruction_Q = conic_Q.has_rational_point(
        point=True
    )
    conic_K = Conic(K, [1, -4*K(L), -K(D)])
    soluble_K, point_or_obstruction_K = conic_K.has_rational_point(
        point=True
    )

    examples.append(
        {
            "parameters": {"a": int(av), "b": int(bv)},
            "branch_polynomial": str(branch_quadratic),
            "branch_field_polynomial": str(K.defining_polynomial()),
            "source_polynomial": str(source_polynomial),
            "source_degree": int(source_polynomial.degree()),
            "target_j": str(j_target),
            "map": {
                "x_coordinate_numerator": str(phi_num),
                "x_coordinate_denominator": str(phi_den),
                "y_multiplier": str(square_multiplier),
                "degree": int(5),
            },
            "normalization_conic": {
                "equation": "y^2 = %s*m^2 + %s*m + %s" % (L, M, N),
                "soluble_over_Q": bool(soluble_Q),
                "Q_point_or_obstruction": str(point_or_obstruction_Q),
                "soluble_over_branch_field": bool(soluble_K),
            },
        }
    )

assert len(examples) >= 8
assert any(
    item["parameters"] == {"a": 7, "b": 1}
    and item["normalization_conic"]["soluble_over_branch_field"]
    for item in examples
)

elapsed = perf_counter() - started
result = {
    "generated_at": datetime.now().astimezone().isoformat(timespec="seconds"),
    "engine": "SageMath 10.8",
    "elapsed_seconds": float(round(elapsed, 6)),
    "workstream": "B002",
    "verified": True,
    "tested_parameter_count": len(examples),
    "Q_soluble_count": int(
        sum(
            item["normalization_conic"]["soluble_over_Q"]
            for item in examples
        )
    ),
    "branch_field_soluble_count": int(
        sum(
            item["normalization_conic"]["soluble_over_branch_field"]
            for item in examples
        )
    ),
    "examples": examples,
    "scope_note": (
        "Every row is an exact genus-2 curve with a certified degree-5 map. "
        "The conic test decides whether the off-diagonal quotient admits a "
        "parametrization over Q or over the branch quadratic field."
    ),
}

output = root / "results" / "sage_degree5_family_census.json"
output.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
print(json.dumps(result, indent=2))
